### ISSUE TITLE
Suggestion: change extension name

### ISSUE THREAD

**Issue by taniarv** [picazoH/spree_sermepa#2]
I would suggest a renaming of the extension in order to include redsys term, which is the actual name of this payment service. 
This gem works like a charm, but it has been very difficult to me to find it. I think that if it is name (or at least documentation) includes some references to Redsys (as sermepa does not exist any longer), many more Spanish developers (yes, we are the only ones who will look for redsys integration) will be able to find and use it.

**Comment by picazoH** [comment]
yep, can you provide a README.md [PR](https://help.github.com/articles/using-pull-requests). I will move the repo soon and refactor the name...
