### ISSUE TITLE
Migración a SHA256

### ISSUE THREAD

**Issue by enoliglesias** [picazoH/spree_sermepa#3]
¡Hola!, habría que actualizar la gema para cifrar la firma con SHA256 en vez de SHA1. Si no, a partir del día 23 de Noviembre, quedará deprecada :( 

A parte del tipo de cifrado, se han realizado cambios también en la forma de enviar los parámetros a Sermepa. Ahora sólo hacen falta 3:
- Ds_SignatureVersion:
  - Versión de la firma: HMAC_SHA256_V1
- Ds_MerchantParameters:
  - JSON codificado en base64 de los parámetros que antes se enviaban en el formulario.
- Ds_Signature
  - Codificación de la clave del banco, junto con los demás parámetros (viene explicado en la documentación)

También cambiaría la forma de comprobar los datos que se reciben.

Se puede acceder a documentación, etc. aquí: https://canales.sermepa.es/canales/ayuda/migracionSHA256.html

Y el PDF en concreto: https://canales.sermepa.es/canales/ayuda/documentacion/Guia%20migracion%20a%20HMAC%20SHA256%20-%20conexion%20por%20redireccion.pdf

¡Un saludo!

**Comment by rsierra** [comment]
+1

**Comment by picazoH** [comment]
Nueva extensión para spree 2.4 y 1.3 
https://github.com/2beDigital/spree_redsys

Alguien sabe que va a pasar con los TPV's basados en https://comercios.ceca.es ?
De momento esta extensión permanecerá para dar soporte a ceca, que parece que no cambia.

**Comment by enoliglesias** [comment]
Gracias! :grinning:  
Ceca en principio no hay cambios.

Un saludo!
